class ForumErrorCode:
    NOT_FOUND = "FORUM_001"
    NOT_AUTHORIZED_EDIT = "FORUM_002"
    NOT_AUTHORIZED_DELETE = "FORUM_003"
    COMMENT_NOT_FOUND = "FORUM_004"
    NOT_AUTHORIZED_EDIT_COMMENT = "FORUM_005"
    NOT_AUTHORIZED_DELETE_COMMENT = "FORUM_006"


MAX_SEARCH_LENGTH = 100
