"""add forum likes and comments tables

Revision ID: 17c5bb3d8f46
Revises: 80636840419f
Create Date: 2025-06-27 17:58:54.567554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17c5bb3d8f46'
down_revision: Union[str, None] = '80636840419f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forums',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('updated_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='cyclopedia_owner'
    )
    op.create_table('posts',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='cyclopedia_owner'
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username'),
    schema='cyclopedia_owner'
    )
    op.create_table('comments',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=False),
    sa.Column('post_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.String(length=255), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['cyclopedia_owner.posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['cyclopedia_owner.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='cyclopedia_owner'
    )
    op.create_table('forum_comments',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=False),
    sa.Column('forum_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.String(length=255), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['forum_id'], ['cyclopedia_owner.forums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['cyclopedia_owner.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='cyclopedia_owner'
    )
    op.create_table('forum_likes',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('forum_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['forum_id'], ['cyclopedia_owner.forums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['cyclopedia_owner.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='cyclopedia_owner'
    )
    op.create_table('post_likes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('post_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['cyclopedia_owner.posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['cyclopedia_owner.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name='_user_post_uc'),
    schema='cyclopedia_owner'
    )
    op.create_table('comment_likes',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('comment_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['cyclopedia_owner.comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['cyclopedia_owner.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='cyclopedia_owner'
    )
    op.create_table('forum_comment_likes',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('comment_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['cyclopedia_owner.forum_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['cyclopedia_owner.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='cyclopedia_owner'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forum_comment_likes', schema='cyclopedia_owner')
    op.drop_table('comment_likes', schema='cyclopedia_owner')
    op.drop_table('post_likes', schema='cyclopedia_owner')
    op.drop_table('forum_likes', schema='cyclopedia_owner')
    op.drop_table('forum_comments', schema='cyclopedia_owner')
    op.drop_table('comments', schema='cyclopedia_owner')
    op.drop_table('users', schema='cyclopedia_owner')
    op.drop_table('posts', schema='cyclopedia_owner')
    op.drop_table('forums', schema='cyclopedia_owner')
    # ### end Alembic commands ###
