name: CI/CD Pipeline

on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      SQL_DB: "postgresql://postgres:postgres@db:5432/tt_cyclopedia"
      TEST_SQL_DB: "sqlite:///./test.db"
      MONGO_DB: "mongodb://mongo:27017"
      MONGO_DB_NAME: tt_cyclopedia

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Poetry
        run: python -m pip install poetry

      - name: Install dependencies with Poetry
        run: poetry install

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Start services with Docker Compose
        run: docker-compose up -d

      - name: Show running containers (before wait)
        run: docker ps -a
      - name: Show Postgres logs (before wait)
        run: |
          docker logs $(docker ps -qf "name=db") || echo "No db logs yet"
      - name: Wait for Postgres to be ready
        run: |
          for i in {1..40}; do
            if docker exec $(docker ps -qf "name=db") pg_isready -U postgres -d tt_cyclopedia; then
              echo "Postgres is ready!"
              exit 0
            fi
            echo "Waiting for Postgres... ($i/40)"
            sleep 5
          done
          echo "Postgres did not become ready in time"
          docker logs $(docker ps -qf "name=db")
          exit 1
      - name: Show running containers (after wait)
        run: docker ps -a
      - name: Show Postgres logs (after wait)
        run: |
          docker logs $(docker ps -qf "name=db") || echo "No db logs yet"

      - name: Clean up test database
        run: |
          rm -f test.db
          echo "Test database cleaned up"

      - name: Run unit tests
        run: poetry run pytest app/tests/*.py::TestSetup --maxfail=10 --disable-warnings -q
