name: CI/CD Pipeline

on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      SQL_DB: ${{ secrets.SQL_DB }}
      TEST_SQL_DB: ${{ secrets.TEST_SQL_DB }}
      MONGO_DB: ${{ secrets.MONGO_DB }}
      MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Poetry
        run: python -m pip install poetry

      - name: Install dependencies with Poetry
        run: poetry install

      - name: Run unit tests
        run: poetry run pytest --maxfail=10 --disable-warnings -q
